# Generated by Django 3.0.2 on 2020-01-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200126_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='intro',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=models.CharField(default='', max_length=20),
        ),
    ]
