# Generated by Django 3.0.2 on 2020-01-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200126_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
