# Generated by Django 3.0.2 on 2020-01-27 16:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('slug', models.SlugField()),
                ('desc', models.TextField()),
                ('pub_date', models.DateField(blank=True, default=datetime.datetime(2020, 1, 27, 16, 40, 7, 902590))),
                ('image', models.ImageField(default='product_pics/default.jpg', upload_to='shop/images')),
                ('category', models.ForeignKey(default='Uncategorized', on_delete=django.db.models.deletion.SET_DEFAULT, to='products.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
