# Generated by Django 3.0.2 on 2020-01-27 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='max_qty',
            field=models.CharField(default=10, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='min_qty',
            field=models.CharField(default=100, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 1, 27, 17, 29, 5, 579232)),
        ),
    ]
