# Generated by Django 3.0.2 on 2020-01-31 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200130_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbooked',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 1, 31, 16, 28, 47, 220643)),
        ),
    ]
