# Generated by Django 3.0.2 on 2020-02-01 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200131_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_user',
            field=models.IntegerField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 2, 1, 16, 29, 54, 366958)),
        ),
        migrations.AlterField(
            model_name='productbooked',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 1, 16, 29, 54, 368023)),
        ),
    ]
