# Generated by Django 3.0.2 on 2020-02-01 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200201_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_pic',
            field=models.ImageField(default='category_images/default.jpg', upload_to='category_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 2, 1, 18, 57, 57, 32445)),
        ),
        migrations.AlterField(
            model_name='productbooked',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 1, 18, 57, 57, 33495)),
        ),
        migrations.AlterField(
            model_name='productbooked',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
