# Generated by Django 3.0.2 on 2020-02-02 14:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0013_auto_20200201_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_priority', models.CharField(choices=[('N', 'Normal'), ('H', 'Hign'), ('L', 'Low')], max_length=10)),
                ('notes_text', models.TextField()),
                ('notes_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 2, 2, 14, 39, 25, 666459)),
        ),
        migrations.AlterField(
            model_name='productbooked',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 2, 14, 39, 25, 667410)),
        ),
        migrations.DeleteModel(
            name='subCategories',
        ),
    ]
