# Generated by Django 3.0.2 on 2020-02-03 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20200203_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 2, 3, 19, 45, 31, 880758)),
        ),
        migrations.AlterField(
            model_name='productbooked',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 3, 19, 45, 31, 881743)),
        ),
        migrations.AlterField(
            model_name='usernotes',
            name='notes_priority',
            field=models.CharField(choices=[('low', 'Low'), ('high', 'High'), ('medium', 'Medium')], max_length=10),
        ),
    ]
